export const specialties = [
  "Cardiologista",
  "Pediatra",
  "Dermatologista",
  "Ortopedista",
  "Neurologista",
  "Ginecologista / Obstetra",
  "Oftalmologista",
  "Oncologista",
  "Psiquiatra",
  "Endocrinologista",
  "Gastroenterologista",
  "Nefrologista",
  "Urologista",
  "Reumatologista",
  "Pneumologista",
  "Hematologista",
  "Infectologista",
  "Otorrinolaringologista",
  "Radiologista",
  "Cirurgião Geral",
  "Anestesiologista",
  "Médico do Trabalho",
  "Médico de Família",
  "Geriatra",
  "Nutrólogo",
  "Angiologista",
  "Cirurgião Plástico",
  "Patologista",
  "Imunologista",
  "Mastologista",
  "Hepatologista",
  "Coloproctologista",
  "Geneticista",
  "Neonatologista",
  "Otoneurologista",
  "Homeopata",
  "Emergencista",
  "Medicina Esportiva",
  "Foniatra",
];
