import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const opesnSans = localFont({
  src: "./fonts/OpenSans-VariableFont_wdth,wght.ttf",
  variable: "--font-open-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Docotor Appointment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${opesnSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
